#!/usr/bin/env bash
#
# Enable tracing
# set -x

# disable annoying messages
export BASH_SILENCE_DEPRECATION_WARNING=1

# zoxide
command -v zoxide &>/dev/null && eval "$(zoxide init --cmd j bash)"

# bash-it
export BASH_IT=$HOME/.bash_it
export BASH_IT_THEME='hawaii50'
export TODO="t"

# bat
export BAT_THEME='Monokai Extended'

# fzf
[[ -f "${HOME}/.fzf.bash" ]] && source "${HOME}/.fzf.bash"

# remove annoying you got mail
unset MAILCHECK

# inputrc
[[ -f "${HOME}/.inputrc" ]] && export INPUTRC="${HOME}/.inputrc"

# vi mode
set -o vi

# os specific
if [[ "$OSTYPE" == "darwin"* ]]; then
    export VISUAL="nvim"
    export EDITOR="$VISUAL"
    export GIT_EDITOR="$VISUAL -f"
fi

if [[ "$OSTYPE" == "linux"* ]]; then
    # procs
    command -v procs &>/dev/null && source <(procs --gen-completion-out bash)
fi

# android
export ANDROID_HVPROTO=ddm

# atuin
command -v atuin &>/dev/null && eval "$(atuin init bash)"

# direnv
command -v direnv &>/dev/null && eval "$(direnv hook bash)"

# lazy loaders
function pyenv() {
    unset -f pyenv
    [[ -f "$HOME/.anyenv/envs/pyenv/.pyenvrc" ]] && source "$HOME/.anyenv/envs/pyenv/.pyenvrc"
    command pyenv $@
}

function nodenv() {
    unset -f nodenv
    [[ -f "$HOME/.anyenv/envs/nodenv/.nodenvrc" ]] && source "$HOME/.anyenv/envs/nodenv/.nodenvrc"
    command nodenv $@
}

# load directly (because of PS1)
[[ -f "$HOME/.anyenv/envs/rbenv/.rbenvrc" ]] && source "$HOME/.anyenv/envs/rbenv/.rbenvrc"

[[ -f "${BASH_IT}/bash_it.sh" ]] && source "$BASH_IT/bash_it.sh"

# load all the bash things
[[ -s "/opt/local/etc/profile.d/bash_completion.sh" ]] && source "/opt/local/etc/profile.d/bash_completion.sh"
[[ -s "${HOME}/.bash_aliases" ]] && source "${HOME}/.bash_aliases"
[[ -s "${HOME}/.bash_functions" ]] && source "${HOME}/.bash_functions"
[[ -s "${HOME}/.bash_local" ]] && source "${HOME}/.bash_local"
[[ -s "${HOME}/.config/op/plugins.sh" ]] && source "${HOME}/.config/op/plugins.sh"

export PATH="$(npm config get prefix)/bin:$PATH"

# PATH fix - removes duplicates, preserves the ordering of paths, and doesn't add a colon at the end.
export PATH="$(echo $PATH | perl -e 'print join(":", grep { not $seen{$_}++ } split(/:/, scalar <>))')"
