#!/bin/bash

# Must define these in .${APP}install file
DROPBOX_DIR=""
GIT_EXEC=""
GIT_REPO=""
APP_CONFIG_FILE=""

APP=$1
APP_INSTALL_CONFIG=".${APP}install"

# does a function exist?
function fn_exists () {
    type $1 2>/dev/null | grep -q 'is a function'      
}

# If .$APPinstall exists, use those variables instead
function load_install_config () {
    if [ -e "$HOME/$APP_INSTALL_CONFIG" ]; then
        . "$HOME/$APP_INSTALL_CONFIG"
    else
        echo "Could not find ${APP_INSTALL_CONFIG} in path.  Must have an install file to continue.  Please fix and try again."
        exit 1
    fi
}

# Create Directory if it doesn't exist
function ensure_directory_exists () {
    DIRECTORY=$1
    if [ ! -d "$DIRECTORY" ]; then
        echo "Creating directory: $DIRECTORY"
        mkdir -p "$DIRECTORY"
    fi

    echo "Directory found: $DIRECTORY"
}

# Update directory from git
function update_from_git () {
    DIRECTORY=$1
    if [ `ls $DIRECTORY | wc -l` -eq 0 ]; then
        $GIT_EXEC clone $GIT_REPO $DIRECTORY
        pushd . > /dev/null
        cd "$DIRECTORY"
        $GIT_EXEC submodule init
        $GIT_EXEC submodule update
        popd > /dev/null
    else
        pushd . > /dev/null
        cd "$DIRECTORY"
        $GIT_EXEC pull origin master
        $GIT_EXEC submodule init
        $GIT_EXEC submodule update
        popd > /dev/null
    fi
}

# Update symlinks (and save previous)
function update_symlink() {
    SYMLINK=$1

    if [ -L "$HOME/${SYMLINK}" ]; then
        EPOCH=`(date +"%s")`
        OLD_SYMLINK="$HOME/${SYMLINK}_$EPOCH"
        cp -RP "$HOME/${SYMLINK}" $OLD_SYMLINK
        rm -rf "$HOME/${SYMLINK}"
        echo "Found existing ${SYMLINK} symlink, copying to $OLD_SYMLINK, removing original."
    elif [ -f "$HOME/${SYMLINK}" ]; then
        EPOCH=`(date +"%s")`
        OLD_FILE="$HOME/${SYMLINK}_$EPOCH"
        mv "$HOME/${SYMLINK}" $OLD_FILE
        echo "Found existing file ${SYMLINK}, renaming to $OLD_FILE."
    fi

    ln -s "$DROPBOX_DIR/${SYMLINK}" "$HOME/${SYMLINK}"

    echo "Created symlink from $HOME/${SYMLINK} to $DROPBOX_DIR/${SYMLINK}"
}

##############################################################################
#
# Begin installation script
#
##############################################################################

load_install_config

ensure_directory_exists $DROPBOX_DIR

update_from_git $DROPBOX_DIR

update_symlink $APP_CONFIG_FILE

fn_exists pre_install
if [ $? -eq 0 ]; then
    pre_install
fi

fn_exists install
if [ $? -eq 0 ]; then
    install
fi

fn_exists post_install
if [ $? -eq 0 ]; then
    post_install
fi

echo "Done."
