#!/bin/bash

DROPBOX_DIR=/Users/ryankanno/Dropbox/Install/dotfiles
GIT_EXEC=/opt/local/bin/git
GIT_REPO=git://github.com/ryankanno/dotfiles.git

# If .viminstall exists, use those variables instead
if [ -d "$HOME/.screeninstall" ]; then
    . "$HOME/.screeninstall"
fi

# Create Dropbox directory
if [ ! -d "$DROPBOX_DIR" ]; then
    echo "Creating Dropbox directory: $DROPBOX_DIR"
    mkdir -p "$DROPBOX_DIR"
fi

echo "Dropbox directory found: $DROPBOX_DIR"

if [ `ls $DROPBOX_DIR | wc -l` -eq 0 ]; then
    $GIT_EXEC clone $GIT_REPO $DROPBOX_DIR
    pushd .
    cd "$DROPBOX_DIR"
    $GIT_EXEC submodule init
    $GIT_EXEC submodule update
    popd
else
    pushd .
    cd "$DROPBOX_DIR"
    $GIT_EXEC pull origin master
    $GIT_EXEC submodule update
    popd
fi

echo "Creating .screen symlinks"

if [ -L "$HOME/.screenrc" ]; then
    EPOCH=`(date +"%s")`
    OLD_SCREENRC="$HOME/.screenrc_$EPOCH"
    cp -RP "$HOME/.screenrc" $OLD_SCREENRC
    rm "$HOME/.screenrc"

    echo "Found existing .screenc symlink, copying to $OLD_SCREENRC, removing original"
fi

ln -s "$DROPBOX_DIR/.screenrc" "$HOME/.screenrc"
echo "Created .screenc symlink"

if [ -L "$HOME/.screen_files" ]; then
    EPOCH=`(date +"%s")`
    OLD_SCREENFILES="$HOME/.screen_files_$EPOCH"
    cp -RP "$HOME/.screen_files" $OLD_SCREENFILES
    rm -rf "$HOME/.screen_files"

    echo "Found existing .screen_files symlink, copying to $OLD_SCREENFILES, removing original"
fi

ln -s "$DROPBOX_DIR/.screen_files" "$HOME/.screen_files"
echo "Created .screen_filessymlink"

echo "Done."
