#!/bin/bash

DROPBOX_DIR=/Users/ryankanno/Dropbox/temp
GIT_EXEC=/opt/local/bin/git
GIT_REPO=git://github.com/ryankanno/vim-config.git

# If .viminstall exists, use those variables instead
if [ -d "$HOME/.viminstall" ]; then
    . "$HOME/.viminstall"
fi

# Create Dropbox directory
if [ ! -d "$DROPBOX_DIR" ]; then
    echo "Creating Dropbox directory: $DROPBOX_DIR"
    mkdir -p "$DROPBOX_DIR"
fi

echo "Dropbox directory found: $DROPBOX_DIR"

if [ `ls $DROPBOX_DIR | wc -l` -eq 0 ]; then
    $GIT_EXEC clone $GIT_REPO $DROPBOX_DIR
    pushd .
    cd "$DROPBOX_DIR"
    $GIT_EXEC submodule init
    $GIT_EXEC submodule update
    popd
else
    pushd .
    cd "$DROPBOX_DIR"
    $GIT_EXEC pull origin master
    $GIT_EXEC submodule update
    popd
fi

echo "Creating .vim symlinks"

if [ -L "$HOME/.vimrc" ]; then
    EPOCH=`(date +"%s")`
    OLD_VIMRC="$HOME/.vimrc_$EPOCH"
    cp -RP "$HOME/.vimrc" $OLD_VIMRC
    rm "$HOME/.vimrc"

    echo "Found existing .vimrc symlink, copying to $OLD_VIMRC, removing original"
fi

ln -s "$DROPBOX_DIR/.vimrc" "$HOME/.vimrc"
echo "Created .vimrc symlink"

if [ -L "$HOME/.vim" ]; then
    EPOCH=`(date +"%s")`
    OLD_VIM="$HOME/.vim_$EPOCH"
    cp -RP "$HOME/.vim" $OLD_VIM
    rm -rf "$HOME/.vim"

    echo "Found existing .vim symlink, copying to $OLD_VIM, removing original"
fi

ln -s "$DROPBOX_DIR/.vim" "$HOME/.vim"
echo "Created .vim symlink"

echo "Done."
