#!/bin/sh

# Returns the count of all your unread Gmail messages

GMAIL_LOGIN=""
GMAIL_PASSWORD=""

if [ -f $HOME/.screen_gmail ]; then
    . $HOME/.screen_gmail
fi

GMAIL_COUNT="$(wget --no-check-certificate -q -O - "https://$GMAIL_LOGIN:$GMAIL_PASSWORD@mail.google.com/mail/feed/atom" | grep 'fullcount' | sed -e 's/<fullcount>\([0-9]*\)<\/fullcount>/\1/g' 2>/dev/null)"

if [ ! -z $GMAIL_COUNT ]; then
    echo $GMAIL_COUNT
else
    echo "!!"
fi
